- name: Filter API
  ansible.builtin.set_fact:
    objects: >-
      {{ objects | combine({
        object.key: {
          'project': api.project | default(connectivity_link.gateway.project.name)
        }}, recursive=True)
      }}
  when: object.value.name == api.name
