- name: Filter enabled Product
  ansible.builtin.set_fact:
    objects: >-
      {{ objects | combine({
        object.key: {
          'enabled': product.enabled | default(true),
          'service': product.service | default(none),
          'introspection': product.introspection | default(false)
        }}, recursive=True)
      }}
  when: object.value.name == product.name
