- name: "Verify Product {{ object.value.name }}"
  ansible.builtin.include_tasks:
    file: enabled_product.yaml
  loop: "{{ threescale.products }}"
  loop_control:
    loop_var: product

- name: "Verify API {{ object.value.name }}"
  ansible.builtin.include_tasks:
    file: api.yaml
  loop: "{{ connectivity_link.apis }}"
  loop_control:
    loop_var: api
