---
- name: Start migration
  hosts: bastions
  tasks:
    - name: Create the Objects store
      ansible.builtin.set_fact:
        objects: {}

    - name: Retrieve all Services
      ansible.builtin.uri:
        url: "{{ threescale.hostname }}/admin/api/services.json?{{ query_parameters | urlencode }}"
      vars:
        query_parameters:
          access_token: "{{ threescale.access_token }}"
      register: output

    - name: Filter by Service ID
      ansible.builtin.set_fact:
        orig_services: "{{ output.json | community.general.json_query('services') }}"

    - name: Filter enabled Services
      ansible.builtin.set_fact:
        services: "{{ orig_services }}"
      loop: "{{ orig_services }}"

    - name: Retrieve all Usages
      ansible.builtin.include_tasks:
        file: usages.yaml
      loop: "{{ services }}"

    - name: Filter enabled services
      ansible.builtin.include_tasks:
        file: filter.yaml
      loop: "{{ objects | dict2items }}"
      loop_control:
        loop_var: object

    - name: Test
      ansible.builtin.debug:
        msg: "{{ objects }}"

    - name: Create Gateway Project
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/project.yaml.j2') | from_yaml }}"
        state: present

    - name: Create GatewayClass instance
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/gatewayclass.yaml.j2') | from_yaml }}"
        state: present

    - name: Create Gateway instance
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/gateway.yaml.j2') | from_yaml }}"
        state: present

    - name: Create Cluter Issuer
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/clusterissuer.yaml.j2') | from_yaml }}"
        state: present

    - name: Create TLS Policy
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/tlspolicy.yaml.j2') | from_yaml }}"
        state: present

    - name: Create other resources
      ansible.builtin.include_tasks:
        file: resources.yaml
      loop: "{{ objects | dict2items }}"
      loop_control:
        loop_var: object
