---
- name: Migrating 3scale configurations to Connectivity Link specifics
  hosts: bastions
  tasks:
    - name: Creation of the data store for collecting relevant information
      ansible.builtin.set_fact:
        objects: {}
        filtered_services: []

    - name: Retrieve the list of all Products on 3scale
      ansible.builtin.uri:
        url: "{{ threescale.hostname }}/admin/api/services.json?{{ query_parameters | urlencode }}"
        validate_certs: "{{ threescale.validate_certs }}"
      vars:
        query_parameters:
          access_token: "{{ threescale.access_token }}"
      register: output

    - name: Cleaning up the information within the set of Products retrieved from 3scale
      ansible.builtin.set_fact:
        services: "{{ output.json | community.general.json_query('services') }}"

    - name: Excluding Products not specified in the execution configuration
      ansible.builtin.include_tasks:
        file: filter_services.yaml
      loop: "{{ services }}"

    - name: Retrieving detailed information for each Product
      ansible.builtin.include_tasks:
        file: usages.yaml
      loop: "{{ filtered_services }}"

    - debug:
        var: objects

    - name: Further reduction of the set of Products to be migrated
      ansible.builtin.include_tasks:
        file: filter_apis.yaml
      loop: "{{ objects | dict2items }}"
      loop_control:
        loop_var: object

    - name: Creation of the Project where the Gateway type instance will be created
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/project.yaml.j2') | from_yaml }}"
        state: present

    - name: Creation of the Gateway type instance
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/gateway.yaml.j2') | from_yaml }}"
        state: present

    - name: Creation of the ClusterIssuer type instance to subsequently issue the necessary certificates
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/clusterissuer.yaml.j2') | from_yaml }}"
        state: present

    - name: Creation of the TLSPolicy type instance to be associated with the Gateway type instance
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/tlspolicy.yaml.j2') | from_yaml }}"
        state: present

    - name: Creation of the other necessary resources
      ansible.builtin.include_tasks:
        file: resources.yaml
      loop: "{{ objects | dict2items }}"
      loop_control:
        loop_var: object
