- name: Extract Service ID
  ansible.builtin.set_fact:
    service_id: "{{ item.service.id }}"

- name: Extract Service System name
  ansible.builtin.set_fact:
    service_name: "{{ item.service.system_name }}"

- name: "Retrieve Usage {{ service_id }}"
  ansible.builtin.uri:
    url: "{{ threescale.hostname }}/admin/api/services/{{ service_id }}/backend_usages.json?{{ query_parameters | urlencode }}"
    validate_certs: "{{ threescale.validate_certs }}"
  vars:
    query_parameters:
      access_token: "{{ threescale.access_token }}"
  register: output_usages

- name: Extract Usage info
  ansible.builtin.set_fact:
    usage: "{{ output_usages.json | first | community.general.json_query('backend_usage.links[?rel==`backend_api`].href') }}"

# - name: Test
#   ansible.builtin.debug:
#     var: usage

- name: Get Backend URL
  ansible.builtin.uri:
    url: "{{ usage[0] }}.json?{{ query_parameters | urlencode }}"
    validate_certs: "{{ threescale.validate_certs }}"
  vars:
    query_parameters:
      access_token: "{{ threescale.access_token }}"
  register: output_backend

- name: Combine with other Usages
  ansible.builtin.set_fact:
    objects: >-
      {{ objects | combine({
        service_id: {
          'enabled': false,
          'name': service_name,
          'endpoint': output_backend.json | community.general.json_query('backend_api.private_endpoint')
        }}, recursive=True)
      }}

- name: Get Application Plans
  ansible.builtin.uri:
    url: "{{ item | community.general.json_query('service.links[?rel==`application_plans`].href') | first }}.json?{{ query_parameters | urlencode }}"
    validate_certs: "{{ threescale.validate_certs }}"
  vars:
    query_parameters:
      access_token: "{{ threescale.access_token }}"
  register: output_app_plans

- name: Check the number of Plans
  ansible.builtin.set_fact:
    n_app_plans: "{{ output_app_plans.json.plans | length }}"

- name: Get active Application Plan
  ansible.builtin.set_fact:
    app_plan_id: "{{ output_app_plans.json.plans | first | community.general.json_query('application_plan.id') }}"
  when: n_app_plans != 0

- name: Get Limits
  ansible.builtin.uri:
    url: "{{ threescale.hostname }}/admin/api/application_plans/{{ app_plan_id }}/limits.json?{{ query_parameters | urlencode }}"
    validate_certs: "{{ threescale.validate_certs }}"
  vars:
    query_parameters:
      access_token: "{{ threescale.access_token }}"
  register: output_app_plan_limits
  when: n_app_plans != 0

- name: Check the number of Limits
  ansible.builtin.set_fact:
    n_app_plan_limits: "{{ output_app_plan_limits.json.limits | length }}"
  when: n_app_plans != 0

- name: Save limit coordinates
  ansible.builtin.set_fact:
    app_plan_period: "{{ output_app_plan_limits.json.limits | first | community.general.json_query('limit.period') }}"
    app_plan_value: "{{ output_app_plan_limits.json.limits | first | community.general.json_query('limit.value') }}"
  when: (n_app_plans != 0) and (n_app_plan_limits != 0)

- name: Combine with other Usages
  ansible.builtin.set_fact:
    objects: >-
      {{ objects | combine({
        service_id: {
          'limits': {
            'period': period_mapping[app_plan_period],
            'value': app_plan_value
          }
        }}, recursive=True)
      }}
  when: (n_app_plans != 0) and (n_app_plan_limits != 0)

- name: Get Applications
  ansible.builtin.uri:
    url: "{{ threescale.hostname }}/admin/api/applications.json?{{ query_parameters | urlencode }}"
    validate_certs: "{{ threescale.validate_certs }}"
  vars:
    query_parameters:
      access_token: "{{ threescale.access_token }}"
      plan_id: "{{ app_plan_id }}"
  register: output_apps
  when: n_app_plans != 0

- name: Check the number of Applications
  ansible.builtin.set_fact:
    n_apps: "{{ output_apps.json.applications | length }}"
  when: n_app_plans != 0

- name: Save credentials
  ansible.builtin.set_fact:
    app_user_key: "{{ output_apps.json.applications | first | community.general.json_query('application.user_key') }}"
    app_client_id: "{{ output_apps.json.applications | first | community.general.json_query('application.client_id') }}"
    app_client_secret: "{{ output_apps.json.applications | first | community.general.json_query('application.client_secret') }}"
  when: (n_app_plans != 0) and (n_apps != 0)

- name: Combine with other Usages
  ansible.builtin.set_fact:
    objects: >-
      {{ objects | combine({
        service_id: {
          'credentials': {
            'user_key': app_user_key,
            'client_id': app_client_id,
            'client_secret': app_client_secret
          }
        }}, recursive=True)
      }}
  when: (n_app_plans != 0) and (n_apps != 0)

- name: Get Proxy
  ansible.builtin.uri:
    url: "{{ threescale.hostname }}/admin/api/services/{{ service_id }}/proxy.json?{{ query_parameters | urlencode }}"
    validate_certs: "{{ threescale.validate_certs }}"
  vars:
    query_parameters:
      access_token: "{{ threescale.access_token }}"
  register: output_proxy

# - ansible.builtin.debug:
#     var: output_proxy

# - name: Save OIDC issuer
#   ansible.builtin.set_fact:
#     oidc_issuer: "{{ output_proxy.json.proxy.oidc_issuer_endpoint | default(none, true) }}"
#   when: output_proxy.json.proxy.oidc_issuer_endpoint is defined

# - ansible.builtin.debug:
#     var: oidc_issuer

# - name: Save OIDC issuer
#   ansible.builtin.set_fact:
#     oidc_issuer: null
#   when: output_proxy.json.proxy.oidc_issuer_endpoint is not defined

- name: Combine with other Usages
  ansible.builtin.set_fact:
    objects: >-
      {{ objects | combine({
        service_id: {
          'credentials': {
            'oidc_issuer': output_proxy.json.proxy.oidc_issuer_endpoint | regex_replace('(https?://)([^@]+@)', '\1')
          }
        }}, recursive=True)
      }}
  when: output_proxy.json.proxy.oidc_issuer_endpoint is defined

- name: Combine with other Usages
  ansible.builtin.set_fact:
    objects: >-
      {{ objects | combine({
        service_id: {
          'credentials': {
            'oidc_issuer': none
          }
        }}, recursive=True)
      }}
  when: output_proxy.json.proxy.oidc_issuer_endpoint is not defined
