ansible_connection: local
ansible_host: localhost
ansible_python_interpreter: "{{ ansible_playbook_python }}"

threescale:
  access_token: ''
  introspection_policy:
    name: jwt_parser
  products:
    - name: api
      enabled: false
    - name: pong
      enabled: true
      # Non serve il Service perché lo posso prendere da 3scale automaticamente
      service:
        name: pong
        hostname: pong.tests.svc.cluster.local
        port: 8080
    - name: pong2
      enabled: true
      introspection: true
      service:
        name: pong
        hostname: pong.tests.svc.cluster.local
        port: 8080
  hostname: https://3scale-admin.apps.cluster-jsn9w.dynamic2.redhatworkshops.io
  validate_certs: false

connectivity_link:
  cluster_issuer: test-ci-1
  gateway:
    class_name: openshift-default
    cluster_issuer: self-signed
    domain:
      base: 'gw1.apps.cluster-jsn9w.dynamic2.redhatworkshops.io'
    name: gw1
    project:
      display_name: api-gateway
      name: api-gateway
  apis:
    - name: pong
      project: tests
    - name: pong2
      project: tests
# url: 'https://sso.apps.cluster-jsn9w.dynamic2.redhatworkshops.io/realms/gws'
# headers:
#   - name: Hdr1
#     op: add
#     value: h1
