apiVersion: kuadrant.io/v1
kind: DNSPolicy
metadata:
  name: ingress-gateway-dnspolicy
  namespace: api-gateway
spec:
  targetRef:
    name: ingress-gateway
    group: gateway.networking.k8s.io
    kind: Gateway
  providerRefs:
  - name: coredns-credentials