driver:
  name: default
platforms:
  - name: dummy
provisioner:
  name: ansible
  inventory:
    links:
      hosts: inventory/openshift.yaml
      host_vars: inventory/host_vars/test_bastion.yaml
scenario:
  test_sequence:
    - dependency
    - syntax
    - converge
