FROM quay.io/fedora/fedora-minimal:44

RUN echo "install_weak_deps=False" >> /etc/dnf/dnf.conf \
 && microdnf --assumeyes install ansible git gzip python3-ansible-lint python3-jmespath python3-kubernetes python3-pip tar \
 && microdnf clean all \
 && pip install molecule molecule-plugins \
 && curl -JLOk https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.20/openshift-client-linux.tar.gz \
 && tar -xzf openshift-client-linux.tar.gz \
 && mv oc /usr/local/bin/ \
 && mv kubectl /usr/local/bin/