apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: ingress-gateway-tls
  namespace: openshift-ingress
spec:
  targetRef:
    name: ingress-gateway
    group: gateway.networking.k8s.io
    kind: Gateway
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: test-ci-1